# Generated by Django 4.2.27 on 2025-12-19 12:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100, unique=True)),
                ('cashPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depositPercent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('interestRate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('max_salary_multiplier', models.DecimalField(decimal_places=2, default=10.0, help_text="Max number of months' salary allowed to purchase", max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('id_number', models.CharField(max_length=13, unique=True)),
                ('birthday', models.DateField()),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('proof_document', models.FileField(blank=True, null=True, upload_to='proof_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loanPrincipal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('loanAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dailyPayment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('selected_phone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='yellow_backend.phone')),
            ],
        ),
    ]
