# Generated by Django 4.2.27 on 2025-12-19 15:56

from django.db import migrations, models
import yellow_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('yellow_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='proof_document',
            field=models.FileField(upload_to=yellow_backend.models.proof_document_upload_path),
        ),
    ]
